# -*- coding: utf-8 -*-
"""在 _detail_html 生成器 §4.14 之后插入「4.14b 认知层新增四指标」专节。"""

P = r'D:\Desktop\基金经理行为分析研究\scripts\_detail_html_20260826.py'
s = open(P, encoding='utf-8').read()

NEW = r'''
# ---------- 4.14b 认知层新增候选：文献挖掘 + 全量实算（2026-09-02） ----------
H.append('<h3 id="c-X2c">4.14b 认知层新增四指标：从文献池挖出的第二增长曲线</h3>')
H.append('<div class="card">')
H.append('<p>继 §4.14 六项落选候选之后，本文换一条路径再挖一轮：<b>不是去外部找新文献，'
         '而是把本地文献库里"提出了测度但本文还没算"的行为偏差直接落成指标</b>。'
         '候选与文献依据全部来自项目文献底库（<code>参考文献/extracted_variables_L5_G*.json</code>），'
         '共提取 4 个认知类候选，全部用真实数据算到基金—季度面板（脚本'
         ' <code>scripts/_l2_new_metrics_20260902.py</code>，结果'
         ' <code>output/L2新增候选_2026-09-02.json</code>）。</p>')
H.append('<h4>数据源（三个既有文件，无新增外购数据）</h4><ul>'
         '<li><b>基金持仓明细_全量修正版_v3.csv</b>：485 只基金 × 96 个报告期'
         '（2002Q3–2026Q2），共 59.2 万条持仓记录；</li>'
         '<li><b>个股月收益率_全量.csv</b>：5,261 只股票的月收益'
         '（2006-01 至 2026-08，57.4 万条），由它重建个股累计净值 nav，'
         '并滚动取 36 个月最高价与 12 个月均价；</li>'
         '<li><b>主分析面板</b>：季度收益、风险暴露（return_volatility）等既有列。</li></ul>')
H.append('<h4>四个候选的定义、计算与文献</h4>'
         '<table><tr><th class="l" style="width:120px">候选</th>'
         '<th class="l">计算公式（逐季→持仓加权→基金层）</th>'
         '<th class="l" style="width:200px">文献依据</th><th style="width:64px">定向</th></tr>'
         '<tr><td class="l"><b>anchor_high<br>锚定效应</b></td>'
         '<td class="l">anchor_high = Σ<sub>i</sub> w<sub>i</sub> × '
         '(P<sub>i,t</sub> ÷ max P<sub>i,过去36月</sub>)<br>'
         '<span class="param">现价距离 36 个月滚动最高价的相对位置，按持仓权重 w 加权；'
         '由月收益重建净值 nav 后取滚动最大值。值域 (0,1]，1＝全部持仓都停在自己的历史高点。</span></td>'
         '<td class="l">池丽旭、庄新田（2011，《管理科学学报》）——历史最高价是重要参考点；'
         'Grinblatt &amp; Han (2005)——参考价格决定买卖压力</td><td>+</td></tr>'
         '<tr><td class="l"><b>cgo<br>资本利得悬垂</b></td>'
         '<td class="l">cgo = Σ<sub>i</sub> w<sub>i</sub> × '
         '(P<sub>i,t</sub> − RefP<sub>i,t</sub>) ÷ RefP<sub>i,t</sub><br>'
         '<span class="param">RefP 取过去 12 个月 nav 均值作成本基础代理'
         '（Grinblatt-Han 原文用换手加权成本，此处等权近似并如实标注）。'
         '值越大＝账面浮盈越厚。</span></td>'
         '<td class="l">Grinblatt &amp; Han (2005, JFE)——处置效应驱动动量的核心变量</td>'
         '<td>+</td></tr>'
         '<tr><td class="l"><b>house_money<br>私房钱效应</b></td>'
         '<td class="l">house_money = 1(R<sub>t−1</sub> &gt; 0) × (σ<sub>t</sub> − σ<sub>t−1</sub>)<br>'
         '<span class="param">上季赚钱之后，本季风险暴露（滚动波动率）上升多少。'
         '上季亏损时记 0——只有"赢了之后加注"才被捕捉。</span></td>'
         '<td class="l">池丽旭、庄新田（2011）；Thaler &amp; Johnson (1990) 私房钱效应理论</td>'
         '<td>+</td></tr>'
         '<tr><td class="l"><b>bhm_shm<br>羊群方向不对称</b></td>'
         '<td class="l">bhm_shm = BHM − SHM<br>'
         '<span class="param">按持仓权重变动方向定义买/卖，对每只股票−季度算买方占比 p，'
         'LSV 框架下分别取 p 高于/低于期望的偏离，得买入羊群度与卖出羊群度，'
         '基金层取均值之差。值越大＝跟买强于跟卖。</span></td>'
         '<td class="l">Wermers (1999) BHM/SHM 分解；李奇泽等（2013）中国基金应用</td>'
         '<td>+</td></tr></table>')
H.append('<h4>检验结果：两显著、两落选</h4>'
         '<table><tr><th class="l" style="width:110px">候选</th>'
         '<th style="width:90px">裸回归 t</th><th style="width:90px">加控制 t</th>'
         '<th style="width:76px">面板 t</th><th style="width:90px">Q5−Q1<br>（分组差）</th>'
         '<th class="l">裁决</th></tr>'
         '<tr><td class="l"><b>anchor_high</b></td><td class="pos">+3.10***</td>'
         '<td class="pos">+3.28***</td><td class="pos">+17.60***</td>'
         '<td>+1.13pp（t=+2.97）</td>'
         '<td class="l"><b>入选认知维度</b>。三道门槛全过；且在含动量因子的 FF4 口径下仍显著'
         '（t=+4.75）——它不是动量暴露的马甲，而是参考点行为本身。</td></tr>'
         '<tr><td class="l"><b>cgo</b></td><td class="pos">+3.76***</td>'
         '<td class="pos">+2.86***</td><td class="pos">+27.80***</td>'
         '<td>+1.08pp（t=+2.98）</td>'
         '<td class="l">通过全部门槛，但与 anchor_high 相关 0.63（同为"现价−参考价"族），'
         '并入后认知维联立 t 由 4.64 降至 4.08、Q5−Q1 由 3.34pp 降至 3.30pp——'
         '<b>信息重复，按"维度内成分须互不冗余"原则未并入，留档备索</b>。'
         '数据补齐真实持仓成本后值得优先复检（RefP 的等权代理偏保守）。</td></tr>'
         '<tr><td class="l"><b>house_money</b></td><td class="pos">+2.14*</td>'
         '<td>0.26 n.s.</td><td>—</td><td>+0.74pp（t=+1.98*）</td>'
         '<td class="l"><b>剔除</b>：裸回归边缘显著、加控制后消失——显著性依赖控制变量，'
         '踩中剔除门槛②；三因变量对照亦只在不对冲风格的口径显著（论文表 3）。</td></tr>'
         '<tr><td class="l"><b>bhm_shm</b></td><td>−0.62 n.s.</td><td>−0.44 n.s.</td>'
         '<td>—</td><td>−0.12pp（t=−0.34）</td>'
         '<td class="l"><b>剔除</b>：三口径均不显著、群体差异为零。买卖双向的羊群在中国基金样本中'
         '相互抵消——与 §4.14 中羊群类候选（抱团度）落选的原因一致。</td></tr></table>')
H.append('<p><b>与 §4.14 的合并结论</b>：两轮扩展共检验 10 个文献候选，'
         '1 个入选（anchor_high）、1 个门槛全过但因冗余未并入（cgo）、8 个落选。'
         '认知维度由 3 成分扩为 4 成分后，单维 t 由 +7.69 升至 <b>+8.15</b>、'
         '联立 t 由 +4.00 升至 <b>+4.64</b>，'
         '综合得分 Q5−Q1 由 +3.13pp 升至 <b>+3.34pp（t=+11.24）</b>——'
         '新成分同时改善了解释力与区分度，且认知—风险应对相关仅升至 0.629（未过 0.7 冗余线）。'
         '这也回应了 §4.8"认知层指标过少"的结构性问题：后续挖潜方向是把'
         ' <code>参考文献/L5_认知行为层</code> 中剩余的处置效应家族测度（FIFO 成本法 CGO、'
         '处置富裕度 CDO 等）逐个落地，而不是再泛化地扫候选。</p>')
H.append('<p class="footnote">方法透明度：所有四指标的计算代码集中在'
         ' <code>scripts/_l2_new_metrics_20260902.py</code>（约 120 行，逐段注释）；'
         '中间产物落盘 <code>output/L2新增候选_面板_2026-09-02.csv</code>（基金—季度面板），'
         '可逐行复核。持仓匹配行情比例 79.6%（缺失季按当日可得持仓加权，缺失不填 0）。</p></div>')
'''

marker = '<p class="footnote"><b>外网检索的诚实说明</b>：本轮尝试用 Exa 与 Jina Reader 做在线文献'
assert marker in s, 'marker not found'
s = s.replace(marker, NEW + '\n' + marker)
open(P, 'w', encoding='utf-8').write(s)
print('inserted 4.14b OK')
